  spring:
    profiles: dev
    datasource:
      url: jdbc:postgresql://localhost:5432/files
      username: postgres
      password: postgres

    jpa:
      hibernate:
        ddl-auto: validate

app:
  aws:
    region: us-east-1
    s3:
      bucket: prueba-bucket
    sns:
      topicArn: arn:aws:sns:us-east-1:123456789012:FileNotification
      endpoint: http://localhost:4566


